### ISSUE TITLE
请教一下作者华为垃圾分类相关问题

### ISSUE THREAD

**Issue by linqinjia** [x670783915/huaweiyun_garbage_classify__learning#1]
作者你好，请教一下你的代码是如何部署到华为modeatrs上的，代码中缺少部署需要的推理代码和配置文件怎么解决，想向大佬请教一下，谢谢哈

**Comment by x670783915** [comment]
只是相关模型用华为云的计算资源训练，数据传上到OBS桶然后开notebook训练即可

**Comment by linqinjia** [comment]
但是训练完要部署到modelarts上进行评分，没有推理代码和配置文件没办法部署，也没有最终的分数

**Comment by linqinjia** [comment]
我现在已经能够在能够完成训练，但是我想上传到系统进行评分，请问大佬这一步是如何进行的，谢谢哈

**Comment by x670783915** [comment]
可能我REAME没有说清楚吧，我当时并没有实际参与哦，你找一下对应的比赛的论坛里面看看吧，我这个主要是满足学校的课题，找了个比赛自己认真做而已，至于你说的评分，如果华为云提供了这个渠道肯定会有文档的，多翻翻就好
